version: 1

# This alignment map enforces coherency for the alignment-map tool itself (dogfooding)

hierarchy:
  requires_human:
    - README.md  # Changes to identity/overview need human review
  technical:
    - SPEC.md

settings:
  line_tolerance: 10
  fuzzy_match: true
  require_complete_coverage: false  # Not enforcing full coverage yet
  respect_gitignore: true
  ignore:
    - "**/tests/**"  # Test files don't require alignment mapping
    - ".gitignore"

mappings:
  # === Core Models ===
  - file: src/alignment_map/models.py
    blocks:
      - name: CheckResult enum
        lines: 13-22
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration with business logic"
        aligned_with:
          - SPEC.md#git-hook-behavior

      - name: LineRange class
        lines: 36-76
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration with validation and overlap detection"
        aligned_with:
          - SPEC.md

      - name: Block class
        lines: 79-96
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration with business logic"
        aligned_with:
          - SPEC.md

      - name: FileMapping class
        lines: 99-213
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration with validation and CRUD methods"
        aligned_with:
          - SPEC.md

      - name: Settings class
        lines: 223-230
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Add ignore and respect_gitignore settings"
        aligned_with:
          - SPEC.md#configuration

      - name: AlignmentMap class
        lines: 233-423
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration with orchestrator methods"
        aligned_with:
          - SPEC.md

      - name: CheckFailure class
        lines: 442-451
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Pydantic migration"
        aligned_with:
          - SPEC.md#error-messages

  # === CLI Commands ===
  - file: src/alignment_map/cli.py
    blocks:
      - name: imports and hook check helper
        lines: 1-49
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Add check_files import and warning when git hook not installed"
        aligned_with:
          - SPEC.md#installation
          - README.md#quick-start

      - name: main entry point
        lines: 50-62
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Add hook check on command invocation"
        aligned_with:
          - SPEC.md#cli-commands

      - name: check command
        lines: 65-106
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Add --tracked option and check_files mode support"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: map-lint command
        lines: 109-226
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Renamed from validate, added --apply workflow"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: block-add command
        lines: 229-305
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Renamed from update, handles overlap strategies"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: block-touch command
        lines: 308-347
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "New command for updating existing block metadata"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: block-suggest command
        lines: 350-386
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Renamed from suggest"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: trace command
        lines: 389-441
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Context printing for file/line locations"
        aligned_with:
          - SPEC.md#cli-commands

      - name: map-graph command
        lines: 444-470
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Renamed from graph"
        aligned_with:
          - SPEC.md#cli-commands
          - README.md#commands

      - name: hook-install command
        lines: 473-518
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Renamed from install-hook"
        aligned_with:
          - SPEC.md#installation
          - README.md#quick-start

  # === Development Installation ===
  - file: src/alignment_map/_install.py
    blocks:
      - name: install hook helper
        lines: 1-37
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Auto-install git hook on development install"
        aligned_with:
          - SPEC.md#installation
          - README.md#quick-start

  - file: setup.py
    blocks:
      - name: custom develop command
        lines: 1-18
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Enable auto-install git hook on setup.py develop"
        aligned_with:
          - SPEC.md#installation
          - README.md#quick-start

  - file: pyproject.toml
    blocks:
      - name: build configuration
        lines: 1-62
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Use legacy build backend for custom commands"
        aligned_with:
          - SPEC.md#installation

  # === Core Checker Logic ===
  - file: src/alignment_map/checker.py
    blocks:
      - name: imports and check_staged_changes function
        lines: 1-50
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Add ignore and gitignore filtering"
        aligned_with:
          - SPEC.md#git-hook-behavior

      - name: check_files function
        lines: 53-141
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "New multi-mode check function (staged/tracked/all/files)"
        aligned_with:
          - SPEC.md#cli-commands

      - name: check_file_change function
        lines: 144-211
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Per-file alignment checking"
        aligned_with:
          - SPEC.md#git-hook-behavior

      - name: check_aligned_document function
        lines: 242-308
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Document staleness checking"
        aligned_with:
          - SPEC.md#git-hook-behavior

      - name: generate suggestions
        lines: 324-364
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Suggestion generation for failures"
        aligned_with:
          - SPEC.md#error-messages

  # === Lint and Auto-fix ===
  - file: src/alignment_map/lint.py
    blocks:
      - name: lint_alignment_map function
        lines: 17-208
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main linting logic with auto/manual fix detection"
        aligned_with:
          - SPEC.md#cli-commands

      - name: detect_line_drift function
        lines: 211-276
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "AST-based line drift detection"
        aligned_with:
          - SPEC.md#fuzzy-line-matching

      - name: apply_fixes_file function
        lines: 293-396
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Auto-fix application from .alignment-map.fixes"
        aligned_with:
          - SPEC.md#cli-commands

  # === Output Formatting ===
  - file: src/alignment_map/output.py
    blocks:
      - name: print_check_results function
        lines: 20-38
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main result output"
        aligned_with:
          - SPEC.md#error-messages

      - name: print_stale_docs function
        lines: 98-130
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Stale document output"
        aligned_with:
          - SPEC.md#error-messages

      - name: print_human_escalation function
        lines: 133-167
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Human escalation output"
        aligned_with:
          - SPEC.md#error-messages

      - name: print_manual_fix_context function
        lines: 170-251
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Context-rich manual fix output"
        aligned_with:
          - SPEC.md#error-messages

      - name: print_block_modification_trace function
        lines: 311-421
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Trace output after block modifications"
        aligned_with:
          - SPEC.md#cli-commands

  # === Update/Add Command Logic ===
  - file: src/alignment_map/update.py
    blocks:
      - name: update_block function
        lines: 20-122
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main block add/update logic"
        aligned_with:
          - SPEC.md#cli-commands

      - name: handle_block_overlap function
        lines: 139-192
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Overlap handling with strategy suggestions"
        aligned_with:
          - SPEC.md#cli-commands

      - name: overlap strategies
        lines: 244-406
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "extend, split, replace strategies"
        aligned_with:
          - SPEC.md#cli-commands

  # === Suggest Command Logic ===
  - file: src/alignment_map/suggest.py
    blocks:
      - name: suggest_blocks function
        lines: 31-75
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main suggestion logic"
        aligned_with:
          - SPEC.md#cli-commands

      - name: suggest_python_blocks function
        lines: 113-181
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "AST-based Python block detection"
        aligned_with:
          - SPEC.md#cli-commands

      - name: print_suggestions function
        lines: 386-436
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Suggestion output formatting"
        aligned_with:
          - SPEC.md#cli-commands

  # === Touch Command Logic ===
  - file: src/alignment_map/touch.py
    blocks:
      - name: touch_block function
        lines: 14-112
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Update existing block metadata with smart line detection"
        aligned_with:
          - SPEC.md#cli-commands

      - name: find_block_current_location function
        lines: 115-164
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "AST-based line detection for moved code"
        aligned_with:
          - SPEC.md#fuzzy-line-matching

  # === Graph Visualization ===
  - file: src/alignment_map/graph.py
    blocks:
      - name: generate_graph function
        lines: 14-41
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main graph generation"
        aligned_with:
          - SPEC.md#cli-commands

      - name: build_graph_data function
        lines: 44-130
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Graph data structure building"
        aligned_with:
          - SPEC.md#cli-commands

      - name: generate_ascii_graph function
        lines: 202-301
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "ASCII tree visualization"
        aligned_with:
          - SPEC.md#cli-commands

  # === Trace Command Logic ===
  - file: src/alignment_map/trace.py
    blocks:
      - name: trace_file_location function
        lines: 16-74
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Main trace logic"
        aligned_with:
          - SPEC.md#cli-commands

      - name: collect_trace_data function
        lines: 77-179
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Trace data collection"
        aligned_with:
          - SPEC.md#cli-commands

      - name: print_trace_output function
        lines: 226-332
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Trace output formatting"
        aligned_with:
          - SPEC.md#cli-commands

  # === Document Parsing ===
  - file: src/alignment_map/parser.py
    blocks:
      - name: extract_document_section function
        lines: 16-68
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Markdown section extraction"
        aligned_with:
          - SPEC.md#document-format

      - name: extract_last_reviewed function
        lines: 71-88
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Frontmatter/comment timestamp extraction"
        aligned_with:
          - SPEC.md#document-format

  # === Git Operations ===
  - file: src/alignment_map/git.py
    blocks:
      - name: get_staged_changes function
        lines: 9-27
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Git staged changes retrieval"
        aligned_with:
          - SPEC.md#git-hook-behavior

      - name: find_project_root function
        lines: 102-144
        last_updated: 2024-01-16T00:00:00
        last_update_comment: "Project root detection with mapfile support"
        aligned_with:
          - SPEC.md#project-root-detection

      - name: get_tracked_files function
        lines: 158-170
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Get all git-tracked files for --tracked mode"
        aligned_with:
          - SPEC.md#cli-commands

      - name: load_gitignore_patterns function
        lines: 171-185
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Load patterns from .gitignore"
        aligned_with:
          - SPEC.md#configuration

      - name: should_ignore_file function
        lines: 186-245
        last_updated: 2025-11-22T00:00:00
        last_update_comment: "Check file against ignore and gitignore patterns"
        aligned_with:
          - SPEC.md#configuration

  # === Documentation ===
  - file: README.md
    blocks:
      - name: Overview
        lines: 1-18
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - SPEC.md#goals

      - name: Quick Start
        lines: 19-30
        last_reviewed: 2025-11-22T00:00:00
        aligned_with:
          - SPEC.md#installation

      - name: Commands
        lines: 71-88
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - SPEC.md#cli-commands

  - file: SPEC.md
    blocks:
      - name: frontmatter
        lines: 1-3
        last_reviewed: 2025-11-22T00:00:00
        aligned_with: []

      - name: Goals
        id: goals
        lines: 11-19
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - README.md#overview

      - name: Alignment Map YAML Schema
        lines: 64-142
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - src/alignment_map/models.py

      - name: Git Hook Behavior
        id: git-hook-behavior
        lines: 171-225
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - src/alignment_map/checker.py

      - name: CLI Commands
        id: cli-commands
        lines: 229-395
        last_reviewed: 2025-11-22T00:00:00
        aligned_with:
          - src/alignment_map/cli.py

      - name: Error Messages
        id: error-messages
        lines: 398-542
        last_reviewed: 2024-11-22T00:00:00
        aligned_with:
          - src/alignment_map/output.py

      - name: Configuration
        id: configuration
        lines: 599-637
        last_reviewed: 2025-11-22T00:00:00
        aligned_with:
          - src/alignment_map/models.py

      - name: Installation
        id: installation
        lines: 563-594
        last_reviewed: 2025-11-22T00:00:00
        aligned_with:
          - README.md#quick-start
